// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: mdm.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_mdm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	MaxAge        int32                  `protobuf:"varint,3,opt,name=maxAge,proto3" json:"maxAge,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Domain        string                 `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	Secure        bool                   `protobuf:"varint,6,opt,name=secure,proto3" json:"secure,omitempty"`
	HttpOnly      bool                   `protobuf:"varint,7,opt,name=httpOnly,proto3" json:"httpOnly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_mdm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *LoginResponse) GetMaxAge() int32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

func (x *LoginResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LoginResponse) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *LoginResponse) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

func (x *LoginResponse) GetHttpOnly() bool {
	if x != nil {
		return x.HttpOnly
	}
	return false
}

type OauthGithubLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OauthGithubLoginRequest) Reset() {
	*x = OauthGithubLoginRequest{}
	mi := &file_mdm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthGithubLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthGithubLoginRequest) ProtoMessage() {}

func (x *OauthGithubLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthGithubLoginRequest.ProtoReflect.Descriptor instead.
func (*OauthGithubLoginRequest) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{2}
}

func (x *OauthGithubLoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type SignupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*SignupRequest_Info
	//	*SignupRequest_File
	Data          isSignupRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupRequest) Reset() {
	*x = SignupRequest{}
	mi := &file_mdm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupRequest) ProtoMessage() {}

func (x *SignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupRequest.ProtoReflect.Descriptor instead.
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{3}
}

func (x *SignupRequest) GetData() isSignupRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SignupRequest) GetInfo() *SignupInfo {
	if x != nil {
		if x, ok := x.Data.(*SignupRequest_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *SignupRequest) GetFile() *AvatarFile {
	if x != nil {
		if x, ok := x.Data.(*SignupRequest_File); ok {
			return x.File
		}
	}
	return nil
}

type isSignupRequest_Data interface {
	isSignupRequest_Data()
}

type SignupRequest_Info struct {
	Info *SignupInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type SignupRequest_File struct {
	File *AvatarFile `protobuf:"bytes,2,opt,name=file,proto3,oneof"`
}

func (*SignupRequest_Info) isSignupRequest_Data() {}

func (*SignupRequest_File) isSignupRequest_Data() {}

type SignupInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Email          string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Nickname       string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Password       string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	AvatarFileName string                 `protobuf:"bytes,4,opt,name=avatarFileName,proto3" json:"avatarFileName,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignupInfo) Reset() {
	*x = SignupInfo{}
	mi := &file_mdm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupInfo) ProtoMessage() {}

func (x *SignupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupInfo.ProtoReflect.Descriptor instead.
func (*SignupInfo) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{4}
}

func (x *SignupInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignupInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *SignupInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignupInfo) GetAvatarFileName() string {
	if x != nil {
		return x.AvatarFileName
	}
	return ""
}

type AvatarFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarFile) Reset() {
	*x = AvatarFile{}
	mi := &file_mdm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarFile) ProtoMessage() {}

func (x *AvatarFile) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarFile.ProtoReflect.Descriptor instead.
func (*AvatarFile) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{5}
}

func (x *AvatarFile) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type UpdateAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UpdateAccountRequest_Info
	//	*UpdateAccountRequest_File
	Data          isUpdateAccountRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountRequest) Reset() {
	*x = UpdateAccountRequest{}
	mi := &file_mdm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountRequest) ProtoMessage() {}

func (x *UpdateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAccountRequest) GetData() isUpdateAccountRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateAccountRequest) GetInfo() *UpdateAccountInfo {
	if x != nil {
		if x, ok := x.Data.(*UpdateAccountRequest_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *UpdateAccountRequest) GetFile() *AvatarFile {
	if x != nil {
		if x, ok := x.Data.(*UpdateAccountRequest_File); ok {
			return x.File
		}
	}
	return nil
}

type isUpdateAccountRequest_Data interface {
	isUpdateAccountRequest_Data()
}

type UpdateAccountRequest_Info struct {
	Info *UpdateAccountInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type UpdateAccountRequest_File struct {
	File *AvatarFile `protobuf:"bytes,2,opt,name=file,proto3,oneof"`
}

func (*UpdateAccountRequest_Info) isUpdateAccountRequest_Data() {}

func (*UpdateAccountRequest_File) isUpdateAccountRequest_Data() {}

type UpdateAccountInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Nickname       string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarFileName string                 `protobuf:"bytes,4,opt,name=avatarFileName,proto3" json:"avatarFileName,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateAccountInfo) Reset() {
	*x = UpdateAccountInfo{}
	mi := &file_mdm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountInfo) ProtoMessage() {}

func (x *UpdateAccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountInfo.ProtoReflect.Descriptor instead.
func (*UpdateAccountInfo) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAccountInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateAccountInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateAccountInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateAccountInfo) GetAvatarFileName() string {
	if x != nil {
		return x.AvatarFileName
	}
	return ""
}

type UpdatePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordRequest) Reset() {
	*x = UpdatePasswordRequest{}
	mi := &file_mdm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRequest) ProtoMessage() {}

func (x *UpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePasswordRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdatePasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_mdm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{9}
}

func (x *AuthRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_mdm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{10}
}

func (x *AuthResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuthResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_mdm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{11}
}

func (x *InfoResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InfoResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InfoResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *InfoResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *InfoResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type InfosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=userIds,proto3" json:"userIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfosRequest) Reset() {
	*x = InfosRequest{}
	mi := &file_mdm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfosRequest) ProtoMessage() {}

func (x *InfosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfosRequest.ProtoReflect.Descriptor instead.
func (*InfosRequest) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{12}
}

func (x *InfosRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type InfosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Infos         []*InfoResponse        `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfosResponse) Reset() {
	*x = InfosResponse{}
	mi := &file_mdm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfosResponse) ProtoMessage() {}

func (x *InfosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfosResponse.ProtoReflect.Descriptor instead.
func (*InfosResponse) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{13}
}

func (x *InfosResponse) GetInfos() []*InfoResponse {
	if x != nil {
		return x.Infos
	}
	return nil
}

type PermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionsRequest) Reset() {
	*x = PermissionsRequest{}
	mi := &file_mdm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionsRequest) ProtoMessage() {}

func (x *PermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionsRequest.ProtoReflect.Descriptor instead.
func (*PermissionsRequest) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{14}
}

func (x *PermissionsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []string               `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionsResponse) Reset() {
	*x = PermissionsResponse{}
	mi := &file_mdm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionsResponse) ProtoMessage() {}

func (x *PermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mdm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionsResponse.ProtoReflect.Descriptor instead.
func (*PermissionsResponse) Descriptor() ([]byte, []int) {
	return file_mdm_proto_rawDescGZIP(), []int{15}
}

func (x *PermissionsResponse) GetRoutes() []string {
	if x != nil {
		return x.Routes
	}
	return nil
}

var File_mdm_proto protoreflect.FileDescriptor

const file_mdm_proto_rawDesc = "" +
	"\n" +
	"\tmdm.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xb1\x01\n" +
	"\rLoginResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06maxAge\x18\x03 \x01(\x05R\x06maxAge\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x16\n" +
	"\x06domain\x18\x05 \x01(\tR\x06domain\x12\x16\n" +
	"\x06secure\x18\x06 \x01(\bR\x06secure\x12\x1a\n" +
	"\bhttpOnly\x18\a \x01(\bR\bhttpOnly\"-\n" +
	"\x17OauthGithubLoginRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"]\n" +
	"\rSignupRequest\x12!\n" +
	"\x04info\x18\x01 \x01(\v2\v.SignupInfoH\x00R\x04info\x12!\n" +
	"\x04file\x18\x02 \x01(\v2\v.AvatarFileH\x00R\x04fileB\x06\n" +
	"\x04data\"\x82\x01\n" +
	"\n" +
	"SignupInfo\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12&\n" +
	"\x0eavatarFileName\x18\x04 \x01(\tR\x0eavatarFileName\"\"\n" +
	"\n" +
	"AvatarFile\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"k\n" +
	"\x14UpdateAccountRequest\x12(\n" +
	"\x04info\x18\x01 \x01(\v2\x12.UpdateAccountInfoH\x00R\x04info\x12!\n" +
	"\x04file\x18\x02 \x01(\v2\v.AvatarFileH\x00R\x04fileB\x06\n" +
	"\x04data\"\x85\x01\n" +
	"\x11UpdateAccountInfo\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12&\n" +
	"\x0eavatarFileName\x18\x04 \x01(\tR\x0eavatarFileName\"K\n" +
	"\x15UpdatePasswordRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"#\n" +
	"\vAuthRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"`\n" +
	"\fAuthResponse\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x128\n" +
	"\texpiresAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xa2\x01\n" +
	"\fInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x128\n" +
	"\tcreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"(\n" +
	"\fInfosRequest\x12\x18\n" +
	"\auserIds\x18\x01 \x03(\x03R\auserIds\"4\n" +
	"\rInfosResponse\x12#\n" +
	"\x05infos\x18\x01 \x03(\v2\r.InfoResponseR\x05infos\",\n" +
	"\x12PermissionsRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"-\n" +
	"\x13PermissionsResponse\x12\x16\n" +
	"\x06routes\x18\x01 \x03(\tR\x06routes2\xfb\x03\n" +
	"\n" +
	"MasterData\x124\n" +
	"\x06Signup\x12\x0e.SignupRequest\x1a\x16.google.protobuf.Empty\"\x00(\x01\x12(\n" +
	"\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponse\"\x00\x12>\n" +
	"\x10OauthGithubLogin\x12\x18.OauthGithubLoginRequest\x1a\x0e.LoginResponse\"\x00\x120\n" +
	"\x06Logout\x12\f.AuthRequest\x1a\x16.google.protobuf.Empty\"\x00\x12B\n" +
	"\rUpdateAccount\x12\x15.UpdateAccountRequest\x1a\x16.google.protobuf.Empty\"\x00(\x01\x12B\n" +
	"\x0eUpdatePassword\x12\x16.UpdatePasswordRequest\x1a\x16.google.protobuf.Empty\"\x00\x12-\n" +
	"\fAuthenticate\x12\f.AuthRequest\x1a\r.AuthResponse\"\x00\x12(\n" +
	"\x05Infos\x12\r.InfosRequest\x1a\x0e.InfosResponse\"\x00\x12:\n" +
	"\vPermissions\x12\x13.PermissionsRequest\x1a\x14.PermissionsResponse\"\x00B\x1eZ\x1c../pkg/space/grpcapi;grpcapib\x06proto3"

var (
	file_mdm_proto_rawDescOnce sync.Once
	file_mdm_proto_rawDescData []byte
)

func file_mdm_proto_rawDescGZIP() []byte {
	file_mdm_proto_rawDescOnce.Do(func() {
		file_mdm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mdm_proto_rawDesc), len(file_mdm_proto_rawDesc)))
	})
	return file_mdm_proto_rawDescData
}

var file_mdm_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_mdm_proto_goTypes = []any{
	(*LoginRequest)(nil),            // 0: LoginRequest
	(*LoginResponse)(nil),           // 1: LoginResponse
	(*OauthGithubLoginRequest)(nil), // 2: OauthGithubLoginRequest
	(*SignupRequest)(nil),           // 3: SignupRequest
	(*SignupInfo)(nil),              // 4: SignupInfo
	(*AvatarFile)(nil),              // 5: AvatarFile
	(*UpdateAccountRequest)(nil),    // 6: UpdateAccountRequest
	(*UpdateAccountInfo)(nil),       // 7: UpdateAccountInfo
	(*UpdatePasswordRequest)(nil),   // 8: UpdatePasswordRequest
	(*AuthRequest)(nil),             // 9: AuthRequest
	(*AuthResponse)(nil),            // 10: AuthResponse
	(*InfoResponse)(nil),            // 11: InfoResponse
	(*InfosRequest)(nil),            // 12: InfosRequest
	(*InfosResponse)(nil),           // 13: InfosResponse
	(*PermissionsRequest)(nil),      // 14: PermissionsRequest
	(*PermissionsResponse)(nil),     // 15: PermissionsResponse
	(*timestamppb.Timestamp)(nil),   // 16: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 17: google.protobuf.Empty
}
var file_mdm_proto_depIdxs = []int32{
	4,  // 0: SignupRequest.info:type_name -> SignupInfo
	5,  // 1: SignupRequest.file:type_name -> AvatarFile
	7,  // 2: UpdateAccountRequest.info:type_name -> UpdateAccountInfo
	5,  // 3: UpdateAccountRequest.file:type_name -> AvatarFile
	16, // 4: AuthResponse.expiresAt:type_name -> google.protobuf.Timestamp
	16, // 5: InfoResponse.createdAt:type_name -> google.protobuf.Timestamp
	11, // 6: InfosResponse.infos:type_name -> InfoResponse
	3,  // 7: MasterData.Signup:input_type -> SignupRequest
	0,  // 8: MasterData.Login:input_type -> LoginRequest
	2,  // 9: MasterData.OauthGithubLogin:input_type -> OauthGithubLoginRequest
	9,  // 10: MasterData.Logout:input_type -> AuthRequest
	6,  // 11: MasterData.UpdateAccount:input_type -> UpdateAccountRequest
	8,  // 12: MasterData.UpdatePassword:input_type -> UpdatePasswordRequest
	9,  // 13: MasterData.Authenticate:input_type -> AuthRequest
	12, // 14: MasterData.Infos:input_type -> InfosRequest
	14, // 15: MasterData.Permissions:input_type -> PermissionsRequest
	17, // 16: MasterData.Signup:output_type -> google.protobuf.Empty
	1,  // 17: MasterData.Login:output_type -> LoginResponse
	1,  // 18: MasterData.OauthGithubLogin:output_type -> LoginResponse
	17, // 19: MasterData.Logout:output_type -> google.protobuf.Empty
	17, // 20: MasterData.UpdateAccount:output_type -> google.protobuf.Empty
	17, // 21: MasterData.UpdatePassword:output_type -> google.protobuf.Empty
	10, // 22: MasterData.Authenticate:output_type -> AuthResponse
	13, // 23: MasterData.Infos:output_type -> InfosResponse
	15, // 24: MasterData.Permissions:output_type -> PermissionsResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_mdm_proto_init() }
func file_mdm_proto_init() {
	if File_mdm_proto != nil {
		return
	}
	file_mdm_proto_msgTypes[3].OneofWrappers = []any{
		(*SignupRequest_Info)(nil),
		(*SignupRequest_File)(nil),
	}
	file_mdm_proto_msgTypes[6].OneofWrappers = []any{
		(*UpdateAccountRequest_Info)(nil),
		(*UpdateAccountRequest_File)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mdm_proto_rawDesc), len(file_mdm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mdm_proto_goTypes,
		DependencyIndexes: file_mdm_proto_depIdxs,
		MessageInfos:      file_mdm_proto_msgTypes,
	}.Build()
	File_mdm_proto = out.File
	file_mdm_proto_goTypes = nil
	file_mdm_proto_depIdxs = nil
}
