// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: mdm.proto

package grpcapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MasterData_Signup_FullMethodName         = "/MasterData/Signup"
	MasterData_Login_FullMethodName          = "/MasterData/Login"
	MasterData_Logout_FullMethodName         = "/MasterData/Logout"
	MasterData_UpdateAccount_FullMethodName  = "/MasterData/UpdateAccount"
	MasterData_UpdatePassword_FullMethodName = "/MasterData/UpdatePassword"
	MasterData_Authenticate_FullMethodName   = "/MasterData/Authenticate"
	MasterData_Infos_FullMethodName          = "/MasterData/Infos"
)

// MasterDataClient is the client API for MasterData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterDataClient interface {
	Signup(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SignupRequest, emptypb.Empty], error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateAccount(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UpdateAccountRequest, emptypb.Empty], error)
	UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Infos(ctx context.Context, in *InfosRequest, opts ...grpc.CallOption) (*InfosResponse, error)
}

type masterDataClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterDataClient(cc grpc.ClientConnInterface) MasterDataClient {
	return &masterDataClient{cc}
}

func (c *masterDataClient) Signup(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SignupRequest, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MasterData_ServiceDesc.Streams[0], MasterData_Signup_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SignupRequest, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MasterData_SignupClient = grpc.ClientStreamingClient[SignupRequest, emptypb.Empty]

func (c *masterDataClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, MasterData_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterDataClient) Logout(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MasterData_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterDataClient) UpdateAccount(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UpdateAccountRequest, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MasterData_ServiceDesc.Streams[1], MasterData_UpdateAccount_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpdateAccountRequest, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MasterData_UpdateAccountClient = grpc.ClientStreamingClient[UpdateAccountRequest, emptypb.Empty]

func (c *masterDataClient) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MasterData_UpdatePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterDataClient) Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, MasterData_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterDataClient) Infos(ctx context.Context, in *InfosRequest, opts ...grpc.CallOption) (*InfosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfosResponse)
	err := c.cc.Invoke(ctx, MasterData_Infos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterDataServer is the server API for MasterData service.
// All implementations must embed UnimplementedMasterDataServer
// for forward compatibility.
type MasterDataServer interface {
	Signup(grpc.ClientStreamingServer[SignupRequest, emptypb.Empty]) error
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *AuthRequest) (*emptypb.Empty, error)
	UpdateAccount(grpc.ClientStreamingServer[UpdateAccountRequest, emptypb.Empty]) error
	UpdatePassword(context.Context, *UpdatePasswordRequest) (*emptypb.Empty, error)
	Authenticate(context.Context, *AuthRequest) (*AuthResponse, error)
	Infos(context.Context, *InfosRequest) (*InfosResponse, error)
	mustEmbedUnimplementedMasterDataServer()
}

// UnimplementedMasterDataServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMasterDataServer struct{}

func (UnimplementedMasterDataServer) Signup(grpc.ClientStreamingServer[SignupRequest, emptypb.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (UnimplementedMasterDataServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedMasterDataServer) Logout(context.Context, *AuthRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedMasterDataServer) UpdateAccount(grpc.ClientStreamingServer[UpdateAccountRequest, emptypb.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method UpdateAccount not implemented")
}
func (UnimplementedMasterDataServer) UpdatePassword(context.Context, *UpdatePasswordRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePassword not implemented")
}
func (UnimplementedMasterDataServer) Authenticate(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedMasterDataServer) Infos(context.Context, *InfosRequest) (*InfosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Infos not implemented")
}
func (UnimplementedMasterDataServer) mustEmbedUnimplementedMasterDataServer() {}
func (UnimplementedMasterDataServer) testEmbeddedByValue()                    {}

// UnsafeMasterDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterDataServer will
// result in compilation errors.
type UnsafeMasterDataServer interface {
	mustEmbedUnimplementedMasterDataServer()
}

func RegisterMasterDataServer(s grpc.ServiceRegistrar, srv MasterDataServer) {
	// If the following call pancis, it indicates UnimplementedMasterDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MasterData_ServiceDesc, srv)
}

func _MasterData_Signup_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MasterDataServer).Signup(&grpc.GenericServerStream[SignupRequest, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MasterData_SignupServer = grpc.ClientStreamingServer[SignupRequest, emptypb.Empty]

func _MasterData_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterDataServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterData_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterDataServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterData_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterDataServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterData_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterDataServer).Logout(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterData_UpdateAccount_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MasterDataServer).UpdateAccount(&grpc.GenericServerStream[UpdateAccountRequest, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MasterData_UpdateAccountServer = grpc.ClientStreamingServer[UpdateAccountRequest, emptypb.Empty]

func _MasterData_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterDataServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterData_UpdatePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterDataServer).UpdatePassword(ctx, req.(*UpdatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterData_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterDataServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterData_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterDataServer).Authenticate(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterData_Infos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterDataServer).Infos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterData_Infos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterDataServer).Infos(ctx, req.(*InfosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MasterData_ServiceDesc is the grpc.ServiceDesc for MasterData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MasterData",
	HandlerType: (*MasterDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _MasterData_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _MasterData_Logout_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _MasterData_UpdatePassword_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _MasterData_Authenticate_Handler,
		},
		{
			MethodName: "Infos",
			Handler:    _MasterData_Infos_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Signup",
			Handler:       _MasterData_Signup_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "UpdateAccount",
			Handler:       _MasterData_UpdateAccount_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "mdm.proto",
}
