// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: srm.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Relation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SrcSubjectType  int32                  `protobuf:"varint,1,opt,name=srcSubjectType,proto3" json:"srcSubjectType,omitempty"`
	SrcSubjectId    int64                  `protobuf:"varint,2,opt,name=srcSubjectId,proto3" json:"srcSubjectId,omitempty"`
	RelationType    int32                  `protobuf:"varint,3,opt,name=relationType,proto3" json:"relationType,omitempty"`
	DestSubjectType int32                  `protobuf:"varint,4,opt,name=destSubjectType,proto3" json:"destSubjectType,omitempty"`
	DestSubjectId   int64                  `protobuf:"varint,5,opt,name=destSubjectId,proto3" json:"destSubjectId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Relation) Reset() {
	*x = Relation{}
	mi := &file_srm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_srm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relation.ProtoReflect.Descriptor instead.
func (*Relation) Descriptor() ([]byte, []int) {
	return file_srm_proto_rawDescGZIP(), []int{0}
}

func (x *Relation) GetSrcSubjectType() int32 {
	if x != nil {
		return x.SrcSubjectType
	}
	return 0
}

func (x *Relation) GetSrcSubjectId() int64 {
	if x != nil {
		return x.SrcSubjectId
	}
	return 0
}

func (x *Relation) GetRelationType() int32 {
	if x != nil {
		return x.RelationType
	}
	return 0
}

func (x *Relation) GetDestSubjectType() int32 {
	if x != nil {
		return x.DestSubjectType
	}
	return 0
}

func (x *Relation) GetDestSubjectId() int64 {
	if x != nil {
		return x.DestSubjectId
	}
	return 0
}

type CheckRelationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relations     []*Relation            `protobuf:"bytes,1,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRelationsRequest) Reset() {
	*x = CheckRelationsRequest{}
	mi := &file_srm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRelationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRelationsRequest) ProtoMessage() {}

func (x *CheckRelationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_srm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRelationsRequest.ProtoReflect.Descriptor instead.
func (*CheckRelationsRequest) Descriptor() ([]byte, []int) {
	return file_srm_proto_rawDescGZIP(), []int{1}
}

func (x *CheckRelationsRequest) GetRelations() []*Relation {
	if x != nil {
		return x.Relations
	}
	return nil
}

type CheckRelationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        []bool                 `protobuf:"varint,1,rep,packed,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRelationsResponse) Reset() {
	*x = CheckRelationsResponse{}
	mi := &file_srm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRelationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRelationsResponse) ProtoMessage() {}

func (x *CheckRelationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_srm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRelationsResponse.ProtoReflect.Descriptor instead.
func (*CheckRelationsResponse) Descriptor() ([]byte, []int) {
	return file_srm_proto_rawDescGZIP(), []int{2}
}

func (x *CheckRelationsResponse) GetExists() []bool {
	if x != nil {
		return x.Exists
	}
	return nil
}

type RelationCount struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SrcSubjectType  int32                  `protobuf:"varint,1,opt,name=srcSubjectType,proto3" json:"srcSubjectType,omitempty"`
	RelationType    int32                  `protobuf:"varint,2,opt,name=relationType,proto3" json:"relationType,omitempty"`
	DestSubjectType int32                  `protobuf:"varint,3,opt,name=destSubjectType,proto3" json:"destSubjectType,omitempty"`
	DestSubjectId   int64                  `protobuf:"varint,4,opt,name=destSubjectId,proto3" json:"destSubjectId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RelationCount) Reset() {
	*x = RelationCount{}
	mi := &file_srm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationCount) ProtoMessage() {}

func (x *RelationCount) ProtoReflect() protoreflect.Message {
	mi := &file_srm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationCount.ProtoReflect.Descriptor instead.
func (*RelationCount) Descriptor() ([]byte, []int) {
	return file_srm_proto_rawDescGZIP(), []int{3}
}

func (x *RelationCount) GetSrcSubjectType() int32 {
	if x != nil {
		return x.SrcSubjectType
	}
	return 0
}

func (x *RelationCount) GetRelationType() int32 {
	if x != nil {
		return x.RelationType
	}
	return 0
}

func (x *RelationCount) GetDestSubjectType() int32 {
	if x != nil {
		return x.DestSubjectType
	}
	return 0
}

func (x *RelationCount) GetDestSubjectId() int64 {
	if x != nil {
		return x.DestSubjectId
	}
	return 0
}

type GetRelationsCountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relations     []*RelationCount       `protobuf:"bytes,1,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationsCountsRequest) Reset() {
	*x = GetRelationsCountsRequest{}
	mi := &file_srm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationsCountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationsCountsRequest) ProtoMessage() {}

func (x *GetRelationsCountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_srm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationsCountsRequest.ProtoReflect.Descriptor instead.
func (*GetRelationsCountsRequest) Descriptor() ([]byte, []int) {
	return file_srm_proto_rawDescGZIP(), []int{4}
}

func (x *GetRelationsCountsRequest) GetRelations() []*RelationCount {
	if x != nil {
		return x.Relations
	}
	return nil
}

type GetRelationsCountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Counts        []int32                `protobuf:"varint,1,rep,packed,name=counts,proto3" json:"counts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationsCountsResponse) Reset() {
	*x = GetRelationsCountsResponse{}
	mi := &file_srm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationsCountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationsCountsResponse) ProtoMessage() {}

func (x *GetRelationsCountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_srm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationsCountsResponse.ProtoReflect.Descriptor instead.
func (*GetRelationsCountsResponse) Descriptor() ([]byte, []int) {
	return file_srm_proto_rawDescGZIP(), []int{5}
}

func (x *GetRelationsCountsResponse) GetCounts() []int32 {
	if x != nil {
		return x.Counts
	}
	return nil
}

var File_srm_proto protoreflect.FileDescriptor

const file_srm_proto_rawDesc = "" +
	"\n" +
	"\tsrm.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xca\x01\n" +
	"\bRelation\x12&\n" +
	"\x0esrcSubjectType\x18\x01 \x01(\x05R\x0esrcSubjectType\x12\"\n" +
	"\fsrcSubjectId\x18\x02 \x01(\x03R\fsrcSubjectId\x12\"\n" +
	"\frelationType\x18\x03 \x01(\x05R\frelationType\x12(\n" +
	"\x0fdestSubjectType\x18\x04 \x01(\x05R\x0fdestSubjectType\x12$\n" +
	"\rdestSubjectId\x18\x05 \x01(\x03R\rdestSubjectId\"@\n" +
	"\x15CheckRelationsRequest\x12'\n" +
	"\trelations\x18\x01 \x03(\v2\t.RelationR\trelations\"0\n" +
	"\x16CheckRelationsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x03(\bR\x06exists\"\xab\x01\n" +
	"\rRelationCount\x12&\n" +
	"\x0esrcSubjectType\x18\x01 \x01(\x05R\x0esrcSubjectType\x12\"\n" +
	"\frelationType\x18\x02 \x01(\x05R\frelationType\x12(\n" +
	"\x0fdestSubjectType\x18\x03 \x01(\x05R\x0fdestSubjectType\x12$\n" +
	"\rdestSubjectId\x18\x04 \x01(\x03R\rdestSubjectId\"I\n" +
	"\x19GetRelationsCountsRequest\x12,\n" +
	"\trelations\x18\x01 \x03(\v2\x0e.RelationCountR\trelations\"4\n" +
	"\x1aGetRelationsCountsResponse\x12\x16\n" +
	"\x06counts\x18\x01 \x03(\x05R\x06counts2\x95\x02\n" +
	"\x0fSubjectRelation\x12C\n" +
	"\x0eCheckRelations\x12\x16.CheckRelationsRequest\x1a\x17.CheckRelationsResponse\"\x00\x12O\n" +
	"\x12GetRelationsCounts\x12\x1a.GetRelationsCountsRequest\x1a\x1b.GetRelationsCountsResponse\"\x00\x125\n" +
	"\x0eCreateRelation\x12\t.Relation\x1a\x16.google.protobuf.Empty\"\x00\x125\n" +
	"\x0eDeleteRelation\x12\t.Relation\x1a\x16.google.protobuf.Empty\"\x00B\x1eZ\x1c../pkg/space/grpcapi;grpcapib\x06proto3"

var (
	file_srm_proto_rawDescOnce sync.Once
	file_srm_proto_rawDescData []byte
)

func file_srm_proto_rawDescGZIP() []byte {
	file_srm_proto_rawDescOnce.Do(func() {
		file_srm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_srm_proto_rawDesc), len(file_srm_proto_rawDesc)))
	})
	return file_srm_proto_rawDescData
}

var file_srm_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_srm_proto_goTypes = []any{
	(*Relation)(nil),                   // 0: Relation
	(*CheckRelationsRequest)(nil),      // 1: CheckRelationsRequest
	(*CheckRelationsResponse)(nil),     // 2: CheckRelationsResponse
	(*RelationCount)(nil),              // 3: RelationCount
	(*GetRelationsCountsRequest)(nil),  // 4: GetRelationsCountsRequest
	(*GetRelationsCountsResponse)(nil), // 5: GetRelationsCountsResponse
	(*emptypb.Empty)(nil),              // 6: google.protobuf.Empty
}
var file_srm_proto_depIdxs = []int32{
	0, // 0: CheckRelationsRequest.relations:type_name -> Relation
	3, // 1: GetRelationsCountsRequest.relations:type_name -> RelationCount
	1, // 2: SubjectRelation.CheckRelations:input_type -> CheckRelationsRequest
	4, // 3: SubjectRelation.GetRelationsCounts:input_type -> GetRelationsCountsRequest
	0, // 4: SubjectRelation.CreateRelation:input_type -> Relation
	0, // 5: SubjectRelation.DeleteRelation:input_type -> Relation
	2, // 6: SubjectRelation.CheckRelations:output_type -> CheckRelationsResponse
	5, // 7: SubjectRelation.GetRelationsCounts:output_type -> GetRelationsCountsResponse
	6, // 8: SubjectRelation.CreateRelation:output_type -> google.protobuf.Empty
	6, // 9: SubjectRelation.DeleteRelation:output_type -> google.protobuf.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_srm_proto_init() }
func file_srm_proto_init() {
	if File_srm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_srm_proto_rawDesc), len(file_srm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_srm_proto_goTypes,
		DependencyIndexes: file_srm_proto_depIdxs,
		MessageInfos:      file_srm_proto_msgTypes,
	}.Build()
	File_srm_proto = out.File
	file_srm_proto_goTypes = nil
	file_srm_proto_depIdxs = nil
}
