// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: srm.proto

package grpcapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubjectRelation_CheckRelations_FullMethodName     = "/SubjectRelation/CheckRelations"
	SubjectRelation_GetRelationsCounts_FullMethodName = "/SubjectRelation/GetRelationsCounts"
	SubjectRelation_CreateRelation_FullMethodName     = "/SubjectRelation/CreateRelation"
	SubjectRelation_DeleteRelation_FullMethodName     = "/SubjectRelation/DeleteRelation"
)

// SubjectRelationClient is the client API for SubjectRelation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubjectRelationClient interface {
	CheckRelations(ctx context.Context, in *CheckRelationsRequest, opts ...grpc.CallOption) (*CheckRelationsResponse, error)
	GetRelationsCounts(ctx context.Context, in *GetRelationsCountsRequest, opts ...grpc.CallOption) (*GetRelationsCountsResponse, error)
	CreateRelation(ctx context.Context, in *Relation, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteRelation(ctx context.Context, in *Relation, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type subjectRelationClient struct {
	cc grpc.ClientConnInterface
}

func NewSubjectRelationClient(cc grpc.ClientConnInterface) SubjectRelationClient {
	return &subjectRelationClient{cc}
}

func (c *subjectRelationClient) CheckRelations(ctx context.Context, in *CheckRelationsRequest, opts ...grpc.CallOption) (*CheckRelationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckRelationsResponse)
	err := c.cc.Invoke(ctx, SubjectRelation_CheckRelations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subjectRelationClient) GetRelationsCounts(ctx context.Context, in *GetRelationsCountsRequest, opts ...grpc.CallOption) (*GetRelationsCountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRelationsCountsResponse)
	err := c.cc.Invoke(ctx, SubjectRelation_GetRelationsCounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subjectRelationClient) CreateRelation(ctx context.Context, in *Relation, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SubjectRelation_CreateRelation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subjectRelationClient) DeleteRelation(ctx context.Context, in *Relation, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SubjectRelation_DeleteRelation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubjectRelationServer is the server API for SubjectRelation service.
// All implementations must embed UnimplementedSubjectRelationServer
// for forward compatibility.
type SubjectRelationServer interface {
	CheckRelations(context.Context, *CheckRelationsRequest) (*CheckRelationsResponse, error)
	GetRelationsCounts(context.Context, *GetRelationsCountsRequest) (*GetRelationsCountsResponse, error)
	CreateRelation(context.Context, *Relation) (*emptypb.Empty, error)
	DeleteRelation(context.Context, *Relation) (*emptypb.Empty, error)
	mustEmbedUnimplementedSubjectRelationServer()
}

// UnimplementedSubjectRelationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubjectRelationServer struct{}

func (UnimplementedSubjectRelationServer) CheckRelations(context.Context, *CheckRelationsRequest) (*CheckRelationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckRelations not implemented")
}
func (UnimplementedSubjectRelationServer) GetRelationsCounts(context.Context, *GetRelationsCountsRequest) (*GetRelationsCountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRelationsCounts not implemented")
}
func (UnimplementedSubjectRelationServer) CreateRelation(context.Context, *Relation) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRelation not implemented")
}
func (UnimplementedSubjectRelationServer) DeleteRelation(context.Context, *Relation) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRelation not implemented")
}
func (UnimplementedSubjectRelationServer) mustEmbedUnimplementedSubjectRelationServer() {}
func (UnimplementedSubjectRelationServer) testEmbeddedByValue()                         {}

// UnsafeSubjectRelationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubjectRelationServer will
// result in compilation errors.
type UnsafeSubjectRelationServer interface {
	mustEmbedUnimplementedSubjectRelationServer()
}

func RegisterSubjectRelationServer(s grpc.ServiceRegistrar, srv SubjectRelationServer) {
	// If the following call pancis, it indicates UnimplementedSubjectRelationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubjectRelation_ServiceDesc, srv)
}

func _SubjectRelation_CheckRelations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRelationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubjectRelationServer).CheckRelations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubjectRelation_CheckRelations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubjectRelationServer).CheckRelations(ctx, req.(*CheckRelationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubjectRelation_GetRelationsCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRelationsCountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubjectRelationServer).GetRelationsCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubjectRelation_GetRelationsCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubjectRelationServer).GetRelationsCounts(ctx, req.(*GetRelationsCountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubjectRelation_CreateRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Relation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubjectRelationServer).CreateRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubjectRelation_CreateRelation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubjectRelationServer).CreateRelation(ctx, req.(*Relation))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubjectRelation_DeleteRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Relation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubjectRelationServer).DeleteRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubjectRelation_DeleteRelation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubjectRelationServer).DeleteRelation(ctx, req.(*Relation))
	}
	return interceptor(ctx, in, info, handler)
}

// SubjectRelation_ServiceDesc is the grpc.ServiceDesc for SubjectRelation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubjectRelation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SubjectRelation",
	HandlerType: (*SubjectRelationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckRelations",
			Handler:    _SubjectRelation_CheckRelations_Handler,
		},
		{
			MethodName: "GetRelationsCounts",
			Handler:    _SubjectRelation_GetRelationsCounts_Handler,
		},
		{
			MethodName: "CreateRelation",
			Handler:    _SubjectRelation_CreateRelation_Handler,
		},
		{
			MethodName: "DeleteRelation",
			Handler:    _SubjectRelation_DeleteRelation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "srm.proto",
}
