// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ucm.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastId        int64                  `protobuf:"varint,1,opt,name=lastId,proto3" json:"lastId,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesRequest) Reset() {
	*x = ListArticlesRequest{}
	mi := &file_ucm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesRequest) ProtoMessage() {}

func (x *ListArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ucm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesRequest.ProtoReflect.Descriptor instead.
func (*ListArticlesRequest) Descriptor() ([]byte, []int) {
	return file_ucm_proto_rawDescGZIP(), []int{0}
}

func (x *ListArticlesRequest) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *ListArticlesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      int64                  `protobuf:"varint,2,opt,name=authorId,proto3" json:"authorId,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	PostedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=postedAt,proto3" json:"postedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleResponse) Reset() {
	*x = ArticleResponse{}
	mi := &file_ucm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleResponse) ProtoMessage() {}

func (x *ArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ucm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleResponse.ProtoReflect.Descriptor instead.
func (*ArticleResponse) Descriptor() ([]byte, []int) {
	return file_ucm_proto_rawDescGZIP(), []int{1}
}

func (x *ArticleResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleResponse) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *ArticleResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleResponse) GetPostedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PostedAt
	}
	return nil
}

type ListArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*ArticleResponse     `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=hasMore,proto3" json:"hasMore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesResponse) Reset() {
	*x = ListArticlesResponse{}
	mi := &file_ucm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesResponse) ProtoMessage() {}

func (x *ListArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ucm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesResponse.ProtoReflect.Descriptor instead.
func (*ListArticlesResponse) Descriptor() ([]byte, []int) {
	return file_ucm_proto_rawDescGZIP(), []int{2}
}

func (x *ListArticlesResponse) GetArticles() []*ArticleResponse {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *ListArticlesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type ArticleDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     int64                  `protobuf:"varint,1,opt,name=articleId,proto3" json:"articleId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleDetailRequest) Reset() {
	*x = ArticleDetailRequest{}
	mi := &file_ucm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleDetailRequest) ProtoMessage() {}

func (x *ArticleDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ucm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleDetailRequest.ProtoReflect.Descriptor instead.
func (*ArticleDetailRequest) Descriptor() ([]byte, []int) {
	return file_ucm_proto_rawDescGZIP(), []int{3}
}

func (x *ArticleDetailRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type ArticleDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *ArticleResponse       `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleDetailResponse) Reset() {
	*x = ArticleDetailResponse{}
	mi := &file_ucm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleDetailResponse) ProtoMessage() {}

func (x *ArticleDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ucm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleDetailResponse.ProtoReflect.Descriptor instead.
func (*ArticleDetailResponse) Descriptor() ([]byte, []int) {
	return file_ucm_proto_rawDescGZIP(), []int{4}
}

func (x *ArticleDetailResponse) GetInfo() *ArticleResponse {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *ArticleDetailResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SearchArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	LastIdx       int32                  `protobuf:"varint,2,opt,name=lastIdx,proto3" json:"lastIdx,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchArticlesRequest) Reset() {
	*x = SearchArticlesRequest{}
	mi := &file_ucm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchArticlesRequest) ProtoMessage() {}

func (x *SearchArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ucm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchArticlesRequest.ProtoReflect.Descriptor instead.
func (*SearchArticlesRequest) Descriptor() ([]byte, []int) {
	return file_ucm_proto_rawDescGZIP(), []int{5}
}

func (x *SearchArticlesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchArticlesRequest) GetLastIdx() int32 {
	if x != nil {
		return x.LastIdx
	}
	return 0
}

func (x *SearchArticlesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      int64                  `protobuf:"varint,2,opt,name=authorId,proto3" json:"authorId,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	PostedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=postedAt,proto3" json:"postedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchArticleResponse) Reset() {
	*x = SearchArticleResponse{}
	mi := &file_ucm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchArticleResponse) ProtoMessage() {}

func (x *SearchArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ucm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchArticleResponse.ProtoReflect.Descriptor instead.
func (*SearchArticleResponse) Descriptor() ([]byte, []int) {
	return file_ucm_proto_rawDescGZIP(), []int{6}
}

func (x *SearchArticleResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchArticleResponse) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *SearchArticleResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchArticleResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SearchArticleResponse) GetPostedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PostedAt
	}
	return nil
}

type SearchArticlesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Articles      []*SearchArticleResponse `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	HasMore       bool                     `protobuf:"varint,2,opt,name=hasMore,proto3" json:"hasMore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchArticlesResponse) Reset() {
	*x = SearchArticlesResponse{}
	mi := &file_ucm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchArticlesResponse) ProtoMessage() {}

func (x *SearchArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ucm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchArticlesResponse.ProtoReflect.Descriptor instead.
func (*SearchArticlesResponse) Descriptor() ([]byte, []int) {
	return file_ucm_proto_rawDescGZIP(), []int{7}
}

func (x *SearchArticlesResponse) GetArticles() []*SearchArticleResponse {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *SearchArticlesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type CommentSectionInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectType   int32                  `protobuf:"varint,1,opt,name=subjectType,proto3" json:"subjectType,omitempty"`
	SubjectId     int64                  `protobuf:"varint,2,opt,name=subjectId,proto3" json:"subjectId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentSectionInfoRequest) Reset() {
	*x = CommentSectionInfoRequest{}
	mi := &file_ucm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentSectionInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentSectionInfoRequest) ProtoMessage() {}

func (x *CommentSectionInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ucm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentSectionInfoRequest.ProtoReflect.Descriptor instead.
func (*CommentSectionInfoRequest) Descriptor() ([]byte, []int) {
	return file_ucm_proto_rawDescGZIP(), []int{8}
}

func (x *CommentSectionInfoRequest) GetSubjectType() int32 {
	if x != nil {
		return x.SubjectType
	}
	return 0
}

func (x *CommentSectionInfoRequest) GetSubjectId() int64 {
	if x != nil {
		return x.SubjectId
	}
	return 0
}

type CommentSectionInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	CommentsCount int32                  `protobuf:"varint,3,opt,name=commentsCount,proto3" json:"commentsCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentSectionInfoResponse) Reset() {
	*x = CommentSectionInfoResponse{}
	mi := &file_ucm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentSectionInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentSectionInfoResponse) ProtoMessage() {}

func (x *CommentSectionInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ucm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentSectionInfoResponse.ProtoReflect.Descriptor instead.
func (*CommentSectionInfoResponse) Descriptor() ([]byte, []int) {
	return file_ucm_proto_rawDescGZIP(), []int{9}
}

func (x *CommentSectionInfoResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentSectionInfoResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CommentSectionInfoResponse) GetCommentsCount() int32 {
	if x != nil {
		return x.CommentsCount
	}
	return 0
}

type CreateCommentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Content          string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CommentSectionId int64                  `protobuf:"varint,3,opt,name=commentSectionId,proto3" json:"commentSectionId,omitempty"`
	ReplyToCommentId *int64                 `protobuf:"varint,4,opt,name=replyToCommentId,proto3,oneof" json:"replyToCommentId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_ucm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ucm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_ucm_proto_rawDescGZIP(), []int{10}
}

func (x *CreateCommentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateCommentRequest) GetCommentSectionId() int64 {
	if x != nil {
		return x.CommentSectionId
	}
	return 0
}

func (x *CreateCommentRequest) GetReplyToCommentId() int64 {
	if x != nil && x.ReplyToCommentId != nil {
		return *x.ReplyToCommentId
	}
	return 0
}

type CreateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int64                  `protobuf:"varint,1,opt,name=commentId,proto3" json:"commentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResponse) Reset() {
	*x = CreateCommentResponse{}
	mi := &file_ucm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResponse) ProtoMessage() {}

func (x *CreateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ucm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return file_ucm_proto_rawDescGZIP(), []int{11}
}

func (x *CreateCommentResponse) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CommentId     int64                  `protobuf:"varint,2,opt,name=commentId,proto3" json:"commentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_ucm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ucm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_ucm_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteCommentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteCommentRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type ListCommentsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CommentSectionId int64                  `protobuf:"varint,1,opt,name=commentSectionId,proto3" json:"commentSectionId,omitempty"`
	LastId           int64                  `protobuf:"varint,2,opt,name=lastId,proto3" json:"lastId,omitempty"`
	Limit            int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListCommentsRequest) Reset() {
	*x = ListCommentsRequest{}
	mi := &file_ucm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsRequest) ProtoMessage() {}

func (x *ListCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ucm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return file_ucm_proto_rawDescGZIP(), []int{13}
}

func (x *ListCommentsRequest) GetCommentSectionId() int64 {
	if x != nil {
		return x.CommentSectionId
	}
	return 0
}

func (x *ListCommentsRequest) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *ListCommentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	RepliesCount  int32                  `protobuf:"varint,4,opt,name=repliesCount,proto3" json:"repliesCount,omitempty"`
	PostedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=postedAt,proto3" json:"postedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentResponse) Reset() {
	*x = CommentResponse{}
	mi := &file_ucm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentResponse) ProtoMessage() {}

func (x *CommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ucm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentResponse.ProtoReflect.Descriptor instead.
func (*CommentResponse) Descriptor() ([]byte, []int) {
	return file_ucm_proto_rawDescGZIP(), []int{14}
}

func (x *CommentResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentResponse) GetRepliesCount() int32 {
	if x != nil {
		return x.RepliesCount
	}
	return 0
}

func (x *CommentResponse) GetPostedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PostedAt
	}
	return nil
}

type ListCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CommentResponse     `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=hasMore,proto3" json:"hasMore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsResponse) Reset() {
	*x = ListCommentsResponse{}
	mi := &file_ucm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsResponse) ProtoMessage() {}

func (x *ListCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ucm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsResponse.ProtoReflect.Descriptor instead.
func (*ListCommentsResponse) Descriptor() ([]byte, []int) {
	return file_ucm_proto_rawDescGZIP(), []int{15}
}

func (x *ListCommentsResponse) GetComments() []*CommentResponse {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *ListCommentsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type ListRepliesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootCommentId int64                  `protobuf:"varint,1,opt,name=rootCommentId,proto3" json:"rootCommentId,omitempty"`
	LastId        int64                  `protobuf:"varint,2,opt,name=lastId,proto3" json:"lastId,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRepliesRequest) Reset() {
	*x = ListRepliesRequest{}
	mi := &file_ucm_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepliesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepliesRequest) ProtoMessage() {}

func (x *ListRepliesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ucm_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepliesRequest.ProtoReflect.Descriptor instead.
func (*ListRepliesRequest) Descriptor() ([]byte, []int) {
	return file_ucm_proto_rawDescGZIP(), []int{16}
}

func (x *ListRepliesRequest) GetRootCommentId() int64 {
	if x != nil {
		return x.RootCommentId
	}
	return 0
}

func (x *ListRepliesRequest) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *ListRepliesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ReplyResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Content          string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	RepliesCount     int32                  `protobuf:"varint,4,opt,name=repliesCount,proto3" json:"repliesCount,omitempty"`
	PostedAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=postedAt,proto3" json:"postedAt,omitempty"`
	ReplyToCommentId *int64                 `protobuf:"varint,6,opt,name=replyToCommentId,proto3,oneof" json:"replyToCommentId,omitempty"`
	ReplyToUserId    *int64                 `protobuf:"varint,7,opt,name=replyToUserId,proto3,oneof" json:"replyToUserId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReplyResponse) Reset() {
	*x = ReplyResponse{}
	mi := &file_ucm_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyResponse) ProtoMessage() {}

func (x *ReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ucm_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyResponse.ProtoReflect.Descriptor instead.
func (*ReplyResponse) Descriptor() ([]byte, []int) {
	return file_ucm_proto_rawDescGZIP(), []int{17}
}

func (x *ReplyResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReplyResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReplyResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReplyResponse) GetRepliesCount() int32 {
	if x != nil {
		return x.RepliesCount
	}
	return 0
}

func (x *ReplyResponse) GetPostedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PostedAt
	}
	return nil
}

func (x *ReplyResponse) GetReplyToCommentId() int64 {
	if x != nil && x.ReplyToCommentId != nil {
		return *x.ReplyToCommentId
	}
	return 0
}

func (x *ReplyResponse) GetReplyToUserId() int64 {
	if x != nil && x.ReplyToUserId != nil {
		return *x.ReplyToUserId
	}
	return 0
}

type ListRepliesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replies       []*ReplyResponse       `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=hasMore,proto3" json:"hasMore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRepliesResponse) Reset() {
	*x = ListRepliesResponse{}
	mi := &file_ucm_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepliesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepliesResponse) ProtoMessage() {}

func (x *ListRepliesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ucm_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepliesResponse.ProtoReflect.Descriptor instead.
func (*ListRepliesResponse) Descriptor() ([]byte, []int) {
	return file_ucm_proto_rawDescGZIP(), []int{18}
}

func (x *ListRepliesResponse) GetReplies() []*ReplyResponse {
	if x != nil {
		return x.Replies
	}
	return nil
}

func (x *ListRepliesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type ScoresStatisticsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*ScoresStatisticsRequest_Filename
	//	*ScoresStatisticsRequest_File
	Data          isScoresStatisticsRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoresStatisticsRequest) Reset() {
	*x = ScoresStatisticsRequest{}
	mi := &file_ucm_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoresStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoresStatisticsRequest) ProtoMessage() {}

func (x *ScoresStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ucm_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoresStatisticsRequest.ProtoReflect.Descriptor instead.
func (*ScoresStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_ucm_proto_rawDescGZIP(), []int{19}
}

func (x *ScoresStatisticsRequest) GetData() isScoresStatisticsRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ScoresStatisticsRequest) GetFilename() string {
	if x != nil {
		if x, ok := x.Data.(*ScoresStatisticsRequest_Filename); ok {
			return x.Filename
		}
	}
	return ""
}

func (x *ScoresStatisticsRequest) GetFile() *File {
	if x != nil {
		if x, ok := x.Data.(*ScoresStatisticsRequest_File); ok {
			return x.File
		}
	}
	return nil
}

type isScoresStatisticsRequest_Data interface {
	isScoresStatisticsRequest_Data()
}

type ScoresStatisticsRequest_Filename struct {
	Filename string `protobuf:"bytes,1,opt,name=filename,proto3,oneof"`
}

type ScoresStatisticsRequest_File struct {
	File *File `protobuf:"bytes,2,opt,name=file,proto3,oneof"`
}

func (*ScoresStatisticsRequest_Filename) isScoresStatisticsRequest_Data() {}

func (*ScoresStatisticsRequest_File) isScoresStatisticsRequest_Data() {}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_ucm_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_ucm_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_ucm_proto_rawDescGZIP(), []int{20}
}

func (x *File) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type ScoresStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoresStatisticsResponse) Reset() {
	*x = ScoresStatisticsResponse{}
	mi := &file_ucm_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoresStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoresStatisticsResponse) ProtoMessage() {}

func (x *ScoresStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ucm_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoresStatisticsResponse.ProtoReflect.Descriptor instead.
func (*ScoresStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_ucm_proto_rawDescGZIP(), []int{21}
}

func (x *ScoresStatisticsResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

var File_ucm_proto protoreflect.FileDescriptor

const file_ucm_proto_rawDesc = "" +
	"\n" +
	"\tucm.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\x13ListArticlesRequest\x12\x16\n" +
	"\x06lastId\x18\x01 \x01(\x03R\x06lastId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x8b\x01\n" +
	"\x0fArticleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bauthorId\x18\x02 \x01(\x03R\bauthorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x126\n" +
	"\bpostedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bpostedAt\"^\n" +
	"\x14ListArticlesResponse\x12,\n" +
	"\barticles\x18\x01 \x03(\v2\x10.ArticleResponseR\barticles\x12\x18\n" +
	"\ahasMore\x18\x02 \x01(\bR\ahasMore\"4\n" +
	"\x14ArticleDetailRequest\x12\x1c\n" +
	"\tarticleId\x18\x01 \x01(\x03R\tarticleId\"W\n" +
	"\x15ArticleDetailResponse\x12$\n" +
	"\x04info\x18\x01 \x01(\v2\x10.ArticleResponseR\x04info\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"a\n" +
	"\x15SearchArticlesRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x18\n" +
	"\alastIdx\x18\x02 \x01(\x05R\alastIdx\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xab\x01\n" +
	"\x15SearchArticleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bauthorId\x18\x02 \x01(\x03R\bauthorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x126\n" +
	"\bpostedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bpostedAt\"f\n" +
	"\x16SearchArticlesResponse\x122\n" +
	"\barticles\x18\x01 \x03(\v2\x16.SearchArticleResponseR\barticles\x12\x18\n" +
	"\ahasMore\x18\x02 \x01(\bR\ahasMore\"[\n" +
	"\x19CommentSectionInfoRequest\x12 \n" +
	"\vsubjectType\x18\x01 \x01(\x05R\vsubjectType\x12\x1c\n" +
	"\tsubjectId\x18\x02 \x01(\x03R\tsubjectId\"j\n" +
	"\x1aCommentSectionInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12$\n" +
	"\rcommentsCount\x18\x03 \x01(\x05R\rcommentsCount\"\xba\x01\n" +
	"\x14CreateCommentRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12*\n" +
	"\x10commentSectionId\x18\x03 \x01(\x03R\x10commentSectionId\x12/\n" +
	"\x10replyToCommentId\x18\x04 \x01(\x03H\x00R\x10replyToCommentId\x88\x01\x01B\x13\n" +
	"\x11_replyToCommentId\"5\n" +
	"\x15CreateCommentResponse\x12\x1c\n" +
	"\tcommentId\x18\x01 \x01(\x03R\tcommentId\"L\n" +
	"\x14DeleteCommentRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1c\n" +
	"\tcommentId\x18\x02 \x01(\x03R\tcommentId\"o\n" +
	"\x13ListCommentsRequest\x12*\n" +
	"\x10commentSectionId\x18\x01 \x01(\x03R\x10commentSectionId\x12\x16\n" +
	"\x06lastId\x18\x02 \x01(\x03R\x06lastId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xaf\x01\n" +
	"\x0fCommentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\"\n" +
	"\frepliesCount\x18\x04 \x01(\x05R\frepliesCount\x126\n" +
	"\bpostedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bpostedAt\"^\n" +
	"\x14ListCommentsResponse\x12,\n" +
	"\bcomments\x18\x01 \x03(\v2\x10.CommentResponseR\bcomments\x12\x18\n" +
	"\ahasMore\x18\x02 \x01(\bR\ahasMore\"h\n" +
	"\x12ListRepliesRequest\x12$\n" +
	"\rrootCommentId\x18\x01 \x01(\x03R\rrootCommentId\x12\x16\n" +
	"\x06lastId\x18\x02 \x01(\x03R\x06lastId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xb0\x02\n" +
	"\rReplyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\"\n" +
	"\frepliesCount\x18\x04 \x01(\x05R\frepliesCount\x126\n" +
	"\bpostedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bpostedAt\x12/\n" +
	"\x10replyToCommentId\x18\x06 \x01(\x03H\x00R\x10replyToCommentId\x88\x01\x01\x12)\n" +
	"\rreplyToUserId\x18\a \x01(\x03H\x01R\rreplyToUserId\x88\x01\x01B\x13\n" +
	"\x11_replyToCommentIdB\x10\n" +
	"\x0e_replyToUserId\"Y\n" +
	"\x13ListRepliesResponse\x12(\n" +
	"\areplies\x18\x01 \x03(\v2\x0e.ReplyResponseR\areplies\x12\x18\n" +
	"\ahasMore\x18\x02 \x01(\bR\ahasMore\"\\\n" +
	"\x17ScoresStatisticsRequest\x12\x1c\n" +
	"\bfilename\x18\x01 \x01(\tH\x00R\bfilename\x12\x1b\n" +
	"\x04file\x18\x02 \x01(\v2\x05.FileH\x00R\x04fileB\x06\n" +
	"\x04data\"\x1c\n" +
	"\x04File\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\".\n" +
	"\x18ScoresStatisticsResponse\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link2\xf0\x04\n" +
	"\vUserContent\x12=\n" +
	"\fListArticles\x12\x14.ListArticlesRequest\x1a\x15.ListArticlesResponse\"\x00\x12@\n" +
	"\rArticleDetail\x12\x15.ArticleDetailRequest\x1a\x16.ArticleDetailResponse\"\x00\x12C\n" +
	"\x0eSearchArticles\x12\x16.SearchArticlesRequest\x1a\x17.SearchArticlesResponse\"\x00\x12O\n" +
	"\x12CommentSectionInfo\x12\x1a.CommentSectionInfoRequest\x1a\x1b.CommentSectionInfoResponse\"\x00\x12@\n" +
	"\rCreateComment\x12\x15.CreateCommentRequest\x1a\x16.CreateCommentResponse\"\x00\x12@\n" +
	"\rDeleteComment\x12\x15.DeleteCommentRequest\x1a\x16.google.protobuf.Empty\"\x00\x12=\n" +
	"\fListComments\x12\x14.ListCommentsRequest\x1a\x15.ListCommentsResponse\"\x00\x12:\n" +
	"\vListReplies\x12\x13.ListRepliesRequest\x1a\x14.ListRepliesResponse\"\x00\x12K\n" +
	"\x10ScoresStatistics\x12\x18.ScoresStatisticsRequest\x1a\x19.ScoresStatisticsResponse\"\x00(\x01B\x1eZ\x1c../pkg/space/grpcapi;grpcapib\x06proto3"

var (
	file_ucm_proto_rawDescOnce sync.Once
	file_ucm_proto_rawDescData []byte
)

func file_ucm_proto_rawDescGZIP() []byte {
	file_ucm_proto_rawDescOnce.Do(func() {
		file_ucm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ucm_proto_rawDesc), len(file_ucm_proto_rawDesc)))
	})
	return file_ucm_proto_rawDescData
}

var file_ucm_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_ucm_proto_goTypes = []any{
	(*ListArticlesRequest)(nil),        // 0: ListArticlesRequest
	(*ArticleResponse)(nil),            // 1: ArticleResponse
	(*ListArticlesResponse)(nil),       // 2: ListArticlesResponse
	(*ArticleDetailRequest)(nil),       // 3: ArticleDetailRequest
	(*ArticleDetailResponse)(nil),      // 4: ArticleDetailResponse
	(*SearchArticlesRequest)(nil),      // 5: SearchArticlesRequest
	(*SearchArticleResponse)(nil),      // 6: SearchArticleResponse
	(*SearchArticlesResponse)(nil),     // 7: SearchArticlesResponse
	(*CommentSectionInfoRequest)(nil),  // 8: CommentSectionInfoRequest
	(*CommentSectionInfoResponse)(nil), // 9: CommentSectionInfoResponse
	(*CreateCommentRequest)(nil),       // 10: CreateCommentRequest
	(*CreateCommentResponse)(nil),      // 11: CreateCommentResponse
	(*DeleteCommentRequest)(nil),       // 12: DeleteCommentRequest
	(*ListCommentsRequest)(nil),        // 13: ListCommentsRequest
	(*CommentResponse)(nil),            // 14: CommentResponse
	(*ListCommentsResponse)(nil),       // 15: ListCommentsResponse
	(*ListRepliesRequest)(nil),         // 16: ListRepliesRequest
	(*ReplyResponse)(nil),              // 17: ReplyResponse
	(*ListRepliesResponse)(nil),        // 18: ListRepliesResponse
	(*ScoresStatisticsRequest)(nil),    // 19: ScoresStatisticsRequest
	(*File)(nil),                       // 20: File
	(*ScoresStatisticsResponse)(nil),   // 21: ScoresStatisticsResponse
	(*timestamppb.Timestamp)(nil),      // 22: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 23: google.protobuf.Empty
}
var file_ucm_proto_depIdxs = []int32{
	22, // 0: ArticleResponse.postedAt:type_name -> google.protobuf.Timestamp
	1,  // 1: ListArticlesResponse.articles:type_name -> ArticleResponse
	1,  // 2: ArticleDetailResponse.info:type_name -> ArticleResponse
	22, // 3: SearchArticleResponse.postedAt:type_name -> google.protobuf.Timestamp
	6,  // 4: SearchArticlesResponse.articles:type_name -> SearchArticleResponse
	22, // 5: CommentResponse.postedAt:type_name -> google.protobuf.Timestamp
	14, // 6: ListCommentsResponse.comments:type_name -> CommentResponse
	22, // 7: ReplyResponse.postedAt:type_name -> google.protobuf.Timestamp
	17, // 8: ListRepliesResponse.replies:type_name -> ReplyResponse
	20, // 9: ScoresStatisticsRequest.file:type_name -> File
	0,  // 10: UserContent.ListArticles:input_type -> ListArticlesRequest
	3,  // 11: UserContent.ArticleDetail:input_type -> ArticleDetailRequest
	5,  // 12: UserContent.SearchArticles:input_type -> SearchArticlesRequest
	8,  // 13: UserContent.CommentSectionInfo:input_type -> CommentSectionInfoRequest
	10, // 14: UserContent.CreateComment:input_type -> CreateCommentRequest
	12, // 15: UserContent.DeleteComment:input_type -> DeleteCommentRequest
	13, // 16: UserContent.ListComments:input_type -> ListCommentsRequest
	16, // 17: UserContent.ListReplies:input_type -> ListRepliesRequest
	19, // 18: UserContent.ScoresStatistics:input_type -> ScoresStatisticsRequest
	2,  // 19: UserContent.ListArticles:output_type -> ListArticlesResponse
	4,  // 20: UserContent.ArticleDetail:output_type -> ArticleDetailResponse
	7,  // 21: UserContent.SearchArticles:output_type -> SearchArticlesResponse
	9,  // 22: UserContent.CommentSectionInfo:output_type -> CommentSectionInfoResponse
	11, // 23: UserContent.CreateComment:output_type -> CreateCommentResponse
	23, // 24: UserContent.DeleteComment:output_type -> google.protobuf.Empty
	15, // 25: UserContent.ListComments:output_type -> ListCommentsResponse
	18, // 26: UserContent.ListReplies:output_type -> ListRepliesResponse
	21, // 27: UserContent.ScoresStatistics:output_type -> ScoresStatisticsResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_ucm_proto_init() }
func file_ucm_proto_init() {
	if File_ucm_proto != nil {
		return
	}
	file_ucm_proto_msgTypes[10].OneofWrappers = []any{}
	file_ucm_proto_msgTypes[17].OneofWrappers = []any{}
	file_ucm_proto_msgTypes[19].OneofWrappers = []any{
		(*ScoresStatisticsRequest_Filename)(nil),
		(*ScoresStatisticsRequest_File)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ucm_proto_rawDesc), len(file_ucm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ucm_proto_goTypes,
		DependencyIndexes: file_ucm_proto_depIdxs,
		MessageInfos:      file_ucm_proto_msgTypes,
	}.Build()
	File_ucm_proto = out.File
	file_ucm_proto_goTypes = nil
	file_ucm_proto_depIdxs = nil
}
