// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: ucm.proto

package grpcapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserContent_ListArticles_FullMethodName       = "/UserContent/ListArticles"
	UserContent_ArticleDetail_FullMethodName      = "/UserContent/ArticleDetail"
	UserContent_CommentSectionInfo_FullMethodName = "/UserContent/CommentSectionInfo"
	UserContent_CreateComment_FullMethodName      = "/UserContent/CreateComment"
	UserContent_DeleteComment_FullMethodName      = "/UserContent/DeleteComment"
	UserContent_ListComments_FullMethodName       = "/UserContent/ListComments"
	UserContent_ListReplies_FullMethodName        = "/UserContent/ListReplies"
	UserContent_ScoresStatistics_FullMethodName   = "/UserContent/ScoresStatistics"
)

// UserContentClient is the client API for UserContent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserContentClient interface {
	ListArticles(ctx context.Context, in *ListArticlesRequest, opts ...grpc.CallOption) (*ListArticlesResponse, error)
	ArticleDetail(ctx context.Context, in *ArticleDetailRequest, opts ...grpc.CallOption) (*ArticleDetailResponse, error)
	CommentSectionInfo(ctx context.Context, in *CommentSectionInfoRequest, opts ...grpc.CallOption) (*CommentSectionInfoResponse, error)
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error)
	ListReplies(ctx context.Context, in *ListRepliesRequest, opts ...grpc.CallOption) (*ListRepliesResponse, error)
	ScoresStatistics(ctx context.Context, in *ScoresStatisticsRequest, opts ...grpc.CallOption) (*ScoresStatisticsResponse, error)
}

type userContentClient struct {
	cc grpc.ClientConnInterface
}

func NewUserContentClient(cc grpc.ClientConnInterface) UserContentClient {
	return &userContentClient{cc}
}

func (c *userContentClient) ListArticles(ctx context.Context, in *ListArticlesRequest, opts ...grpc.CallOption) (*ListArticlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArticlesResponse)
	err := c.cc.Invoke(ctx, UserContent_ListArticles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userContentClient) ArticleDetail(ctx context.Context, in *ArticleDetailRequest, opts ...grpc.CallOption) (*ArticleDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleDetailResponse)
	err := c.cc.Invoke(ctx, UserContent_ArticleDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userContentClient) CommentSectionInfo(ctx context.Context, in *CommentSectionInfoRequest, opts ...grpc.CallOption) (*CommentSectionInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentSectionInfoResponse)
	err := c.cc.Invoke(ctx, UserContent_CommentSectionInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userContentClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserContent_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userContentClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserContent_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userContentClient) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommentsResponse)
	err := c.cc.Invoke(ctx, UserContent_ListComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userContentClient) ListReplies(ctx context.Context, in *ListRepliesRequest, opts ...grpc.CallOption) (*ListRepliesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRepliesResponse)
	err := c.cc.Invoke(ctx, UserContent_ListReplies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userContentClient) ScoresStatistics(ctx context.Context, in *ScoresStatisticsRequest, opts ...grpc.CallOption) (*ScoresStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoresStatisticsResponse)
	err := c.cc.Invoke(ctx, UserContent_ScoresStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserContentServer is the server API for UserContent service.
// All implementations must embed UnimplementedUserContentServer
// for forward compatibility.
type UserContentServer interface {
	ListArticles(context.Context, *ListArticlesRequest) (*ListArticlesResponse, error)
	ArticleDetail(context.Context, *ArticleDetailRequest) (*ArticleDetailResponse, error)
	CommentSectionInfo(context.Context, *CommentSectionInfoRequest) (*CommentSectionInfoResponse, error)
	CreateComment(context.Context, *CreateCommentRequest) (*emptypb.Empty, error)
	DeleteComment(context.Context, *DeleteCommentRequest) (*emptypb.Empty, error)
	ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error)
	ListReplies(context.Context, *ListRepliesRequest) (*ListRepliesResponse, error)
	ScoresStatistics(context.Context, *ScoresStatisticsRequest) (*ScoresStatisticsResponse, error)
	mustEmbedUnimplementedUserContentServer()
}

// UnimplementedUserContentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserContentServer struct{}

func (UnimplementedUserContentServer) ListArticles(context.Context, *ListArticlesRequest) (*ListArticlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListArticles not implemented")
}
func (UnimplementedUserContentServer) ArticleDetail(context.Context, *ArticleDetailRequest) (*ArticleDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArticleDetail not implemented")
}
func (UnimplementedUserContentServer) CommentSectionInfo(context.Context, *CommentSectionInfoRequest) (*CommentSectionInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentSectionInfo not implemented")
}
func (UnimplementedUserContentServer) CreateComment(context.Context, *CreateCommentRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedUserContentServer) DeleteComment(context.Context, *DeleteCommentRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedUserContentServer) ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListComments not implemented")
}
func (UnimplementedUserContentServer) ListReplies(context.Context, *ListRepliesRequest) (*ListRepliesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReplies not implemented")
}
func (UnimplementedUserContentServer) ScoresStatistics(context.Context, *ScoresStatisticsRequest) (*ScoresStatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScoresStatistics not implemented")
}
func (UnimplementedUserContentServer) mustEmbedUnimplementedUserContentServer() {}
func (UnimplementedUserContentServer) testEmbeddedByValue()                     {}

// UnsafeUserContentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserContentServer will
// result in compilation errors.
type UnsafeUserContentServer interface {
	mustEmbedUnimplementedUserContentServer()
}

func RegisterUserContentServer(s grpc.ServiceRegistrar, srv UserContentServer) {
	// If the following call pancis, it indicates UnimplementedUserContentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserContent_ServiceDesc, srv)
}

func _UserContent_ListArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserContentServer).ListArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserContent_ListArticles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserContentServer).ListArticles(ctx, req.(*ListArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserContent_ArticleDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserContentServer).ArticleDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserContent_ArticleDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserContentServer).ArticleDetail(ctx, req.(*ArticleDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserContent_CommentSectionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentSectionInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserContentServer).CommentSectionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserContent_CommentSectionInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserContentServer).CommentSectionInfo(ctx, req.(*CommentSectionInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserContent_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserContentServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserContent_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserContentServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserContent_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserContentServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserContent_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserContentServer).DeleteComment(ctx, req.(*DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserContent_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserContentServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserContent_ListComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserContentServer).ListComments(ctx, req.(*ListCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserContent_ListReplies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRepliesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserContentServer).ListReplies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserContent_ListReplies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserContentServer).ListReplies(ctx, req.(*ListRepliesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserContent_ScoresStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoresStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserContentServer).ScoresStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserContent_ScoresStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserContentServer).ScoresStatistics(ctx, req.(*ScoresStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserContent_ServiceDesc is the grpc.ServiceDesc for UserContent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserContent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UserContent",
	HandlerType: (*UserContentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListArticles",
			Handler:    _UserContent_ListArticles_Handler,
		},
		{
			MethodName: "ArticleDetail",
			Handler:    _UserContent_ArticleDetail_Handler,
		},
		{
			MethodName: "CommentSectionInfo",
			Handler:    _UserContent_CommentSectionInfo_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _UserContent_CreateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _UserContent_DeleteComment_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _UserContent_ListComments_Handler,
		},
		{
			MethodName: "ListReplies",
			Handler:    _UserContent_ListReplies_Handler,
		},
		{
			MethodName: "ScoresStatistics",
			Handler:    _UserContent_ScoresStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ucm.proto",
}
