package errno

// generated by parser
const (
	OK        = "00000" // 一切ok	正确执行后的返回
	ClientErr = "A0001" // 用户端错误	一级宏观错误码

	RegistrationErr            = "A0100" // 用户注册错误	二级宏观错误码
	PrivacyPolicyNotAccepted   = "A0101" // 用户未同意隐私协议
	RegistrationAreaRestricted = "A0102" // 注册国家或地区受限

	InvalidUsername       = "A0110" // 用户名校验失败
	ExistedUsername       = "A0111" // 用户名已存在
	SensitiveUsername     = "A0112" // 用户名包含敏感词
	IllegalCharInUsername = "A0113" // 用户名包含特殊字符

	InvalidPassword = "A0120" // 密码校验失败
	ShortPassword   = "A0121" // 密码长度不够
	WeakPassword    = "A0122" // 密码强度不够

	IncorrectVerificationCode      = "A0130" // 校验码输入错误
	IncorrectSMSVerificationCode   = "A0131" // 短信校验码输入错误
	IncorrectEmailVerificationCode = "A0132" // 邮件校验码输入错误
	IncorrectVoiceVerificationCode = "A0133" // 语音校验码输入错误

	InvalidDocumentation   = "A0140" // 用户证件异常
	DocumentationNotChosen = "A0141" // 用户证件类型未选择
	InvalidIDCardNum       = "A0142" // 大陆身份证编号校验非法
	InvalidPassportNum     = "A0143" // 护照编号校验非法
	InvalidMilitaryID      = "A0144" // 军官证编号校验非法

	InvalidBasicInfo = "A0150" // 用户基本信息校验失败
	InvalidPhoneNum  = "A0151" // 手机格式校验失败
	InvalidAddress   = "A0152" // 地址格式校验失败
	InvalidEmail     = "A0153" // 邮箱格式校验失败

	AbnormalLogin = "A0200" // 用户登录异常	二级宏观错误码
	UserNotFound  = "A0201" // 用户账户不存在
	UserFrozen    = "A0202" // 用户账户被冻结
	UserInvalid   = "A0203" // 用户账户已作废

	IncorrectPassword        = "A0210" // 用户密码错误
	TooManyIncorrectPassword = "A0211" // 用户输入密码错误次数超限

	IdentityUnrecognized        = "A0220" // 用户身份校验失败
	FingerprintUnrecognized     = "A0221" // 用户指纹识别失败
	FaceUnrecognized            = "A0222" // 用户面容识别失败
	ThirdPartyLoginUnauthorized = "A0223" // 用户未获得第三方登录授权

	LoginExpired = "A0230" // 用户登录已过期

	WrongCaptcha        = "A0240" // 用户验证码错误
	TooManyWrongCaptcha = "A0241" // 用户验证码尝试次数超限

	AccessRightAbnormal = "A0300" // 访问权限异常	二级宏观错误码
	AccessUnauthorized  = "A0301" // 访问未授权
	Authorizing         = "A0302" // 正在授权中
	AuthorizationDenied = "A0303" // 用户授权申请被拒绝

	AccessRestrictedPrivacy = "A0310" // 因访问对象隐私设置被拦截
	AuthorizationExpired    = "A0311" // 授权已过期
	APIForbidden            = "A0312" // 无权限使用API

	AccessDenied            = "A0320" // 用户访问被拦截
	BlacklistUser           = "A0321" // 黑名单用户
	AccountFrozen           = "A0322" // 账号被冻结
	IllegalIP               = "A0323" // 非法IP地址
	GatewayAccessRestricted = "A0324" // 网关访问受限
	BlacklistArea           = "A0325" // 地域黑名单

	OutOfCredit = "A0330" // 服务已欠费

	SignatureAbnormal    = "A0340" // 用户签名异常
	RSASignatureAbnormal = "A0341" // RSA签名错误

	WrongParam         = "A0400" // 用户请求参数错误	二级宏观错误码
	MaliciousLinkFound = "A0401" // 包含非法恶意跳转链接
	InvalidInput       = "A0402" // 无效的用户输入

	RequiredParamEmpty = "A0410" // 请求必填参数为空
	OrderNumEmpty      = "A0411" // 用户订单号为空
	OrderQuantityEmpty = "A0412" // 订购数量为空
	TimeParamEmpty     = "A0413" // 缺少时间戳参数
	IllegalTimeParam   = "A0414" // 非法的时间戳参数

	ParamOutOfRange       = "A0420" // 请求参数值超出允许的范围
	ParamFormatUnexpected = "A0421" // 参数格式不匹配
	AddressOutOfRange     = "A0422" // 地址不在服务范围
	TimeOutOfRange        = "A0423" // 时间不在服务范围
	AmountOutOfRange      = "A0424" // 金额超出限制
	NumberOutOfRange      = "A0425" // 数量超出限制
	TotalBatchOutOfRange  = "A0426" // 请求批量处理总个数超出限制
	JSONParseErr          = "A0427" // 请求JSON解析失败

	IllegalContent        = "A0430" // 用户输入内容非法
	IllegalWord           = "A0431" // 包含违禁敏感词
	IllegalPicture        = "A0432" // 图片包含违禁信息
	CopyrightInfringement = "A0433" // 文件侵犯版权

	OperationAbnormal         = "A0440" // 用户操作异常
	PaymentOvertime           = "A0441" // 用户支付超时
	OrderConfirmationOvertime = "A0442" // 确认订单超时
	OrderCancelled            = "A0443" // 订单已关闭

	UserRequestAbnormal       = "A0500" // 用户请求服务异常	二级宏观错误码
	TooManyRequests           = "A0501" // 请求次数超出限制
	TooManyRequestConcurrency = "A0502" // 请求并发数超出限制
	OperationWait             = "A0503" // 用户操作请等待
	WebsocketConnAbnormal     = "A0504" // WebSocket连接异常
	WebsocketDisconnected     = "A0505" // WebSocket连接断开
	DuplicateRequest          = "A0506" // 用户重复请求

	UserResourceAbnormal = "A0600" // 用户资源异常	二级宏观错误码
	InsufficientBalance  = "A0601" // 账户余额不足
	InsufficientDisk     = "A0602" // 用户磁盘空间不足
	InsufficientRAM      = "A0603" // 用户内存空间不足
	InsufficientOSSSpace = "A0604" // 用户OSS容量不足
	OutOfQuota           = "A0605" // 用户配额已用光	蚂蚁森林浇水数或每天抽奖数

	FileUploadAbnormal     = "A0700" // 用户上传文件异常	二级宏观错误码
	UnexpectedFileType     = "A0701" // 用户上传文件类型不匹配
	FileTooLarge           = "A0702" // 用户上传文件太大
	PictureTooLarge        = "A0703" // 用户上传图片太大
	VideoTooLarge          = "A0704" // 用户上传视频太大
	CompressedFileTooLarge = "A0705" // 用户上传压缩文件太大

	VersionAbnormal      = "A0800" // 用户当前版本异常	二级宏观错误码
	VersionMismatched    = "A0801" // 用户安装版本与系统不匹配
	VersionTooLow        = "A0802" // 用户安装版本过低
	VersionTooHigh       = "A0803" // 用户安装版本过高
	VersionOutdated      = "A0804" // 用户安装版本已过期
	UnexpectedAPIVersion = "A0805" // 用户API请求版本不匹配
	APIVersionTooHigh    = "A0806" // 用户API请求版本过高
	APIVersionTooLow     = "A0807" // 用户API请求版本过低

	UserPrivacyUnauthorized = "A0900" // 用户隐私未授权	二级宏观错误码
	UserPrivacyUnsigned     = "A0901" // 用户隐私未签署
	WebcamUnauthorized      = "A0902" // 用户摄像头未授权
	CameraUnauthorized      = "A0903" // 用户相机未授权
	AlbumUnauthorized       = "A0904" // 用户图片库未授权
	FileUnauthorized        = "A0905" // 用户文件未授权
	LocationUnauthorized    = "A0906" // 用户位置信息未授权
	ContactsUnauthorized    = "A0907" // 用户通讯录未授权

	UserDeviceAbnormal = "A1000" // 用户设备异常	二级宏观错误码
	CameraAbnormal     = "A1001" // 用户相机异常
	MicrophoneAbnormal = "A1002" // 用户麦克风异常
	ReceiverAbnormal   = "A1003" // 用户听筒异常
	SpeakerAbnormal    = "A1004" // 用户扬声器异常
	GPSAbnormal        = "A1005" // 用户GPS定位异常
	SystemErr          = "B0001" // 系统执行出错	一级宏观错误码

	SystemExecTimeout   = "B0100" // 系统执行超时	二级宏观错误码
	OrderProcessTimeout = "B0101" // 系统订单处理超时

	DisasterRecovery = "B0200" // 系统容灾功能被触发	二级宏观错误码

	SystemRateLimited = "B0210" // 系统限流

	SystemFunctionDowngrade = "B0220" // 系统功能降级

	SystemResourceAbnormal = "B0300" // 系统资源异常	二级宏观错误码

	SystemResourceExhausted = "B0310" // 系统资源耗尽
	DiskSpaceExhausted      = "B0311" // 系统磁盘空间耗尽
	RAMExhausted            = "B0312" // 系统内存耗尽
	FileHandleExhausted     = "B0313" // 文件句柄耗尽
	ConnPoolExhausted       = "B0314" // 系统连接池耗尽
	ThreadPoolExhausted     = "B0315" // 系统线程池耗尽

	SystemResourceAccessAbnormal = "B0320" // 系统资源访问异常
	FileAccessErr                = "B0321" // 系统读取磁盘文件失败
	ThirdPartyErr                = "C0001" // 调用第三方服务出错	一级宏观错误码

	MiddlewareServiceErr = "C0100" // 中间件服务出错	二级宏观错误码

	RPCServiceErr           = "C0110" // RPC服务出错
	RPCServiceNotFound      = "C0111" // RPC服务未找到
	RPCServiceNotRegistered = "C0112" // RPC服务未注册
	InterfaceNotFound       = "C0113" // 接口不存在

	MQServiceErr      = "C0120" // 消息服务出错
	MQDeliveryErr     = "C0121" // 消息投递出错
	MQConsumptionErr  = "C0122" // 消息消费出错
	MQSubscriptionErr = "C0123" // 消息订阅出错
	MQGroupNotFound   = "C0124" // 消息分组未查到

	CacheServiceErr            = "C0130" // 缓存服务出错
	CacheKeyLengthTooLong      = "C0131" // key长度超过限制
	CacheValueLengthTooLong    = "C0132" // value长度超过限制
	FullCacheStorage           = "C0133" // 存储容量已满
	UnsupportedCacheDataFormat = "C0134" // 不支持的数据格式

	ConfigServiceErr = "C0140" // 配置服务出错

	NetworkServiceErr = "C0150" // 网络资源服务出错
	VPNServiceErr     = "C0151" // VPN服务出错
	CDNServiceErr     = "C0152" // CDN服务出错
	DNSServiceErr     = "C0153" // 域名解析服务出错
	GatewayServiceErr = "C0154" // 网关服务出错

	ThirdPartyServiceTimeout = "C0200" // 第三方系统执行超时	二级宏观错误码

	RPCServiceTimeout = "C0210" // RPC执行超时

	MQDeliveryTimeout = "C0220" // 消息投递超时

	CacheServiceTimeout = "C0230" // 缓存服务超时

	ConfigServiceTimeout = "C0240" // 配置服务超时

	DatabaseServiceTimeout = "C0250" // 数据库服务超时

	DatabaseServiceErr = "C0300" // 数据库服务出错	二级宏观错误码

	DBTableNotFound  = "C0311" // 表不存在
	DBColumnNotFound = "C0312" // 列不存在

	DuplicateColumnJoined = "C0321" // 多表关联中存在多个相同名称的列

	DBDeadlock = "C0331" // 数据库死锁

	DBPrimaryKeyConflict = "C0341" // 主键冲突

	ThirdPartyDisasterRecovery  = "C0400" // 第三方容灾系统被触发	二级宏观错误码
	ThirdPartyRateLimited       = "C0401" // 第三方系统限流
	ThirdPartyFunctionDowngrade = "C0402" // 第三方功能降级

	NotificationServiceErr      = "C0500" // 通知服务出错	二级宏观错误码
	SMSNotificationServiceErr   = "C0501" // 短信提醒服务失败
	VoiceNotificationServiceErr = "C0502" // 语音提醒服务失败
	EmailNotificationServiceErr = "C0503" // 邮件提醒服务失败
)
