package errno

// generated by parser
var ErrorStatus = map[string]int{
	OK:        200,
	ClientErr: 400,

	RegistrationErr:            400,
	PrivacyPolicyNotAccepted:   400,
	RegistrationAreaRestricted: 400,

	InvalidUsername:       400,
	ExistedUsername:       400,
	SensitiveUsername:     400,
	IllegalCharInUsername: 400,

	InvalidPassword: 400,
	ShortPassword:   400,
	WeakPassword:    400,

	IncorrectVerificationCode:      400,
	IncorrectSMSVerificationCode:   400,
	IncorrectEmailVerificationCode: 400,
	IncorrectVoiceVerificationCode: 400,

	InvalidDocumentation:   400,
	DocumentationNotChosen: 400,
	InvalidIDCardNum:       400,
	InvalidPassportNum:     400,
	InvalidMilitaryID:      400,

	InvalidBasicInfo: 400,
	InvalidPhoneNum:  400,
	InvalidAddress:   400,
	InvalidEmail:     400,

	AbnormalLogin: 400,
	UserNotFound:  404,
	UserFrozen:    400,
	UserInvalid:   400,

	IncorrectPassword:        400,
	TooManyIncorrectPassword: 403,

	IdentityUnrecognized:        400,
	FingerprintUnrecognized:     400,
	FaceUnrecognized:            400,
	ThirdPartyLoginUnauthorized: 401,

	LoginExpired: 401,

	WrongCaptcha:        400,
	TooManyWrongCaptcha: 403,

	AccessRightAbnormal: 400,
	AccessUnauthorized:  401,
	Authorizing:         401,
	AuthorizationDenied: 403,

	AccessRestrictedPrivacy: 403,
	AuthorizationExpired:    401,
	APIForbidden:            403,

	AccessDenied:            403,
	BlacklistUser:           403,
	AccountFrozen:           403,
	IllegalIP:               403,
	GatewayAccessRestricted: 403,
	BlacklistArea:           403,

	OutOfCredit: 400,

	SignatureAbnormal:    400,
	RSASignatureAbnormal: 400,

	WrongParam:         400,
	MaliciousLinkFound: 400,
	InvalidInput:       400,

	RequiredParamEmpty: 400,
	OrderNumEmpty:      400,
	OrderQuantityEmpty: 400,
	TimeParamEmpty:     400,
	IllegalTimeParam:   400,

	ParamOutOfRange:       400,
	ParamFormatUnexpected: 400,
	AddressOutOfRange:     400,
	TimeOutOfRange:        400,
	AmountOutOfRange:      400,
	NumberOutOfRange:      400,
	TotalBatchOutOfRange:  400,
	JSONParseErr:          400,

	IllegalContent:        400,
	IllegalWord:           400,
	IllegalPicture:        400,
	CopyrightInfringement: 400,

	OperationAbnormal:         400,
	PaymentOvertime:           400,
	OrderConfirmationOvertime: 400,
	OrderCancelled:            400,

	UserRequestAbnormal:       400,
	TooManyRequests:           429,
	TooManyRequestConcurrency: 429,
	OperationWait:             400,
	WebsocketConnAbnormal:     400,
	WebsocketDisconnected:     400,
	DuplicateRequest:          400,

	UserResourceAbnormal: 400,
	InsufficientBalance:  400,
	InsufficientDisk:     400,
	InsufficientRAM:      400,
	InsufficientOSSSpace: 400,
	OutOfQuota:           400,

	FileUploadAbnormal:     400,
	UnexpectedFileType:     400,
	FileTooLarge:           413,
	PictureTooLarge:        413,
	VideoTooLarge:          413,
	CompressedFileTooLarge: 413,

	VersionAbnormal:      400,
	VersionMismatched:    400,
	VersionTooLow:        400,
	VersionTooHigh:       400,
	VersionOutdated:      400,
	UnexpectedAPIVersion: 400,
	APIVersionTooHigh:    400,
	APIVersionTooLow:     400,

	UserPrivacyUnauthorized: 401,
	UserPrivacyUnsigned:     401,
	WebcamUnauthorized:      401,
	CameraUnauthorized:      401,
	AlbumUnauthorized:       401,
	FileUnauthorized:        401,
	LocationUnauthorized:    401,
	ContactsUnauthorized:    401,

	UserDeviceAbnormal: 400,
	CameraAbnormal:     400,
	MicrophoneAbnormal: 400,
	ReceiverAbnormal:   400,
	SpeakerAbnormal:    400,
	GPSAbnormal:        400,
	SystemErr:          500,

	SystemExecTimeout:   500,
	OrderProcessTimeout: 500,

	DisasterRecovery: 503,

	SystemRateLimited: 503,

	SystemFunctionDowngrade: 503,

	SystemResourceAbnormal: 500,

	SystemResourceExhausted: 500,
	DiskSpaceExhausted:      500,
	RAMExhausted:            500,
	FileHandleExhausted:     500,
	ConnPoolExhausted:       500,
	ThreadPoolExhausted:     500,

	SystemResourceAccessAbnormal: 500,
	FileAccessErr:                500,
	ThirdPartyErr:                500,

	MiddlewareServiceErr: 500,

	RPCServiceErr:           500,
	RPCServiceNotFound:      500,
	RPCServiceNotRegistered: 500,
	InterfaceNotFound:       500,

	MQServiceErr:      500,
	MQDeliveryErr:     500,
	MQConsumptionErr:  500,
	MQSubscriptionErr: 500,
	MQGroupNotFound:   500,

	CacheServiceErr:            500,
	CacheKeyLengthTooLong:      500,
	CacheValueLengthTooLong:    500,
	FullCacheStorage:           500,
	UnsupportedCacheDataFormat: 500,

	ConfigServiceErr: 500,

	NetworkServiceErr: 500,
	VPNServiceErr:     500,
	CDNServiceErr:     500,
	DNSServiceErr:     500,
	GatewayServiceErr: 500,

	ThirdPartyServiceTimeout: 500,

	RPCServiceTimeout: 500,

	MQDeliveryTimeout: 500,

	CacheServiceTimeout: 500,

	ConfigServiceTimeout: 500,

	DatabaseServiceTimeout: 500,

	DatabaseServiceErr: 500,

	DBTableNotFound:  500,
	DBColumnNotFound: 500,

	DuplicateColumnJoined: 500,

	DBDeadlock: 500,

	DBPrimaryKeyConflict: 500,

	ThirdPartyDisasterRecovery:  500,
	ThirdPartyRateLimited:       500,
	ThirdPartyFunctionDowngrade: 500,

	NotificationServiceErr:      500,
	SMSNotificationServiceErr:   500,
	VoiceNotificationServiceErr: 500,
	EmailNotificationServiceErr: 500,
}
