# import json
# import os
# from cv2 import dft
# import pandas


# def generate_go(df: pandas.DataFrame, file: str):
#     with open(os.path.expanduser(file), 'w') as f:
#         f.write('''package errno

# // generated by parser
# const (
# ''')
#         i_prev = 0
#         for row in df.itertuples():
#             i = int(row[1][1:])
#             if abs(i-i_prev) > 1:
#                 f.write('\n')
#             i_prev = i
#             f.write(f'\t{row[4]} = "{row[1]}" // {row[2]}\t{row[3]}\n')
#         f.write(')')


# def generate_map_go(df: pandas.DataFrame, file: str):
#     with open(os.path.expanduser(file), 'w') as f:
#         f.write('''package errno

# type Error struct {
# 	Code    string
# 	Message string
# 	Status  int
# }

# var ErrMap = map[string]Error{
# ''')
#         i_prev = 0
#         for row in df.itertuples():
#             i = int(row[1][1:])
#             if abs(i-i_prev) > 1:
#                 f.write('\n')
#             i_prev = i
#             f.write('\t%s :  {Code: "%s", Message: "%s", Status: %d},\n' % (
#                 row[4], row[1], row[6], row[5]))
#         f.write('}')


# def separate(s: str):
#     if len(s) <= 1:
#         return s
#     r = []
#     word_start_idx = None
#     for i in range(len(s)):
#         if s[i].isupper() and word_start_idx is None:
#             word_start_idx = i
#         elif i+1 == len(s):
#             r.append(s[word_start_idx:i+1])
#             word_start_idx = None
#         elif s[i].islower() and s[i+1].isupper():
#             r.append(s[word_start_idx:i+1])
#             word_start_idx = None
#         elif s[i].isupper() and s[i+1].islower():
#             r.append(s[word_start_idx:i])
#             word_start_idx = i
#     return ' '.join(r)


# if __name__ == '__main__':
#     df = pandas.read_csv('./errorcode.csv', sep=',', keep_default_na=False)
#     # generate_go(df, '../code.go')
#     generate_map_go(df, '../error.go')
#     # print(df['变量名'][0])
#     # df['消息'] = ''
#     # for i in range(len(df['消息'])):
#     #     df['消息'][i] = separate(df['变量名'][i])
#     # df.to_csv('errorcode.csv', index=False)
