package restful

import "fmt"

type Error struct {
	Code    string
	Message string
	Status  int
}

func (e *Error) Error() string {
	return fmt.Sprintf("restful.Error(%v-%v):%v", e.Status, e.Code, e.Message)
}

// generated by errcode_gen.go
var (
{{- range .}}
    {{.VarName}} = &Error{Code: "{{.Code}}", Message: "{{.Message}}", Status: {{.Status}}} // {{.DescCn}} {{.Comment}}
{{- end}}
)
